modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="sleep_vote_skip"
version="${version}"
displayName="Sleep Vote Skip"
authors="Aether_254"
description='''Starts a server-wide vote when a player sleeps and skips to morning after a majority votes yes.'''

[[dependencies.sleep_vote_skip]]
modId="neoforge"
type="required"
versionRange="[21.1.219,)"
ordering="NONE"
side="BOTH"

[[dependencies.sleep_vote_skip]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.sleep_vote_skip]]
modId="cloth_config"
type="required"
versionRange="[15.0.140,)"
ordering="AFTER"
side="BOTH"
