modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="compass_overlay"
version="${version}"
displayName="Compass Overlay"
authors="Aether_254"
description='''Shows the player's cardinal heading and yaw while a compass is present in the inventory.'''

[[dependencies.compass_overlay]]
modId="neoforge"
type="required"
versionRange="[21.1.219,)"
ordering="NONE"
side="CLIENT"

[[dependencies.compass_overlay]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="CLIENT"

[[dependencies.compass_overlay]]
modId="cloth_config"
type="required"
versionRange="[15.0.140,)"
ordering="AFTER"
side="CLIENT"
